name: dplpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pandas
  - numpy
  - scipy
  - statsmodels
  - matplotlib
  - ipykernel
  - pip
  - pip:
    - csaps
    - jupyterlab
    - notebook
    - pytest
